name: Hello World!

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Enable manual triggering

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
