name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # This action fetches the source code from the repository
      - name: "Setup node v16"
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build project
        run: npm run build